//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public string ProductTitle { get; set; }
        public int Quantity { get; set; }
        public int UnitPrice { get; set; }
        public int TotatlPrice { get; set; }
        public int ProductId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
